global:
  scrape_interval: 1m
  scrape_timeout: 10s
  external_labels:
    namespace: prod
    app: monitoring
    service: prometheus

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: mimir
    static_configs:
      - targets: ["mimir.monitoring.koyeb:8080"]
  - job_name: blackbox # To get metrics about the exporter itself
    metrics_path: /metrics
    static_configs:
      - targets:
        - blackbox-exporter.monitoring.koyeb:9115
  - job_name: http_wcb
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: [westclimbingbank.org]
    static_configs:
      - targets:
        - blackbox-exporter.monitoring.koyeb:9115
  - job_name: http_zam
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: [www.zam-milano.it]
    static_configs:
      - targets:
        - blackbox-exporter.monitoring.koyeb:9115
  - job_name: http_unit
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: [unit.abbiamoundominio.org]
    static_configs:
      - targets:
        - blackbox-exporter.monitoring.koyeb:9115


remote_write:
  - url: http://mimir-lb.monitoring.koyeb:9009/api/v1/push
    headers:
      X-Scope-OrgID: prod
